In [1]:
import tensorflow as tf

In [2]:
## data 선언
x_data =[[1.],[2.],[3.],[4.]]
y_data =[[1.],[3.],[5.],[7.]]

In [10]:
## 평균 0, 분산 1의 파라미터의 정규분포로 부터 값을 가져옴.
# 학습을 통해 업데이트가 되어 변화되는 모델의 파라미터인 w,b를 의미한다.
W=tf.Variable(tf.random.normal((1,1),mean=0, stddev=1.0))
b=tf.Variable(tf.random.normal((1,1),mean=0, stddev=1.0))
lr=tf.constant(0.1)

In [12]:
for i in range(2000):  ## 에폭
    total_error = 0

    for j in range(len(x_data)): ## 배치 1
        ## data * weight
        WX =tf.matmul([x_data[j]], W)

        ## bias add
        y_hat = tf.add(WX, b)

        ## 정답인 Y와 출력값의 error 계산
        error = tf.subtract(y_data[j], y_hat)

        ## 경사하강법으로 W와 b 업데이트.
        ## 도함수 구하기
        diff_W = tf.multiply(([x_data[j]]), error)
        diff_b = error

        ##  업데이트할 만큼 러닝레이트 곱
        diff_W = tf.multiply(diff_W, lr)
        diff_b = tf.multiply(diff_b, lr)

        ## w, b 업데이트
        W = tf.add(W, diff_W)
        b = tf.add(b, diff_b)

        print(W, b)



        ## 토탈 에러.
        visual_error = tf.square(tf.subtract(y_data[j], y_hat))
        total_error = total_error + visual_error

    ## 모든 데이터에 따른 error 값
    print("epoch: ", i, "error : ", total_error/len(x_data))

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
tf.Tensor([[1.9999998]], shape=(1, 1), dtype=float32) tf.Tensor([[-0.99999934]], shape=(1, 1), dtype=float32)
tf.Tensor([[1.9999998]], shape=(1, 1), dtype=float32) tf.Tensor([[-0.99999934]], shape=(1, 1), dtype=float32)
tf.Tensor([[1.9999999]], shape=(1, 1), dtype=float32) tf.Tensor([[-0.9999993]], shape=(1, 1), dtype=float32)
tf.Tensor([[1.9999999]], shape=(1, 1), dtype=float32) tf.Tensor([[-0.9999993]], shape=(1, 1), dtype=float32)
epoch:  1000 error :  tf.Tensor([[1.5987212e-13]], shape=(1, 1), dtype=float32)
tf.Tensor([[1.9999998]], shape=(1, 1), dtype=float32) tf.Tensor([[-0.99999934]], shape=(1, 1), dtype=float32)
tf.Tensor([[1.9999998]], shape=(1, 1), dtype=float32) tf.Tensor([[-0.99999934]], shape=(1, 1), dtype=float32)
tf.Tensor([[1.9999999]], shape=(1, 1), dtype=float32) tf.Tensor([[-0.9999993]], shape=(1, 1), dtype=float32)
tf.Tensor([[1.9999999]], shape=(1, 1), dtype=float32) tf.Tensor([[-0.9999993]], shape=(1, 1), dtype=float32)
epoch:  

In [13]:
print("W : ", W)
print("b : ", b)
print("input 3 : ", tf.add(tf.multiply(9,W), b))

W :  tf.Tensor([[1.9999999]], shape=(1, 1), dtype=float32)
b :  tf.Tensor([[-0.9999993]], shape=(1, 1), dtype=float32)
input 3 :  tf.Tensor([[16.999998]], shape=(1, 1), dtype=float32)
